### PR TITLE
added SSO login and removed CMS,GPO

### PR DESCRIPTION
**Pull request by arya2331**

### CODE REVIEW

**Comment by pulsejet** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/page/quick-links/quick-links.component.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wncc/instiapp-angular/pullRequest?prid=6311199&bid=20521461)

**Comment by e-aakash** [comment]
Please fix the lint error
https://access.iitb.ac.in/ can be added under Misc as CC Web Services Access Portal or just CC Access Portal

**Comment by pulsejet** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/page/quick-links/quick-links.component.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wncc/instiapp-angular/pullRequest?prid=6311199&bid=20521461)

**Comment by pulsejet** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/page/quick-links/quick-links.component.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wncc/instiapp-angular/pullRequest?prid=6311199&bid=20521461)

**Comment by pulsejet** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/page/quick-links/quick-links.component.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wncc/instiapp-angular/pullRequest?prid=6311199&bid=20521461)

**Comment by pulsejet** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/app/page/quick-links/quick-links.component.ts  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/wncc/instiapp-angular/pullRequest?prid=6311199&bid=20521461)

**Comment by e-aakash** [comment]
Can you squash the commits and update the PR? Also, "added links to ..." would be a better name for the pr :)
Please follow [GNOME commit message guidelines](https://wiki.gnome.org/Git/CommitMessages) for the squashed commit.

**Review by e-aakash — APPROVED** [review]
Good work. Thanks! 👍

**Pull request merged**
